# Generated by Django 6.0.6 on 2026-07-13 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('hash_documento', models.CharField(blank=True, max_length=64)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('hash_anterior', models.CharField(default='0', max_length=64)),
                ('hash_bloque', models.CharField(blank=True, max_length=64)),
                ('payload', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmar_documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
